server:
  port: 10010

spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: d7160cc7-7feb-4f19-b8c1-6960128b6f8c
        cluster-name: Xian
        ephemeral: false
    gateway:
      routes:
        - id: adminservice # 路由标示，必须唯一
          uri: lb://adminservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则，符合形式的才能通过
            - Path=/tag/** # 路径断言，判断路径是否是以/user开头，如果是则符合

        - id: blogservice
          uri: lb://blogservice
          predicates:
            - Path=/article/**, /category/**, /comment/**

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:  # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods:  # 允许的跨域ajax请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"  # 允许携带头部信息
            allowCredentials: true  # 允许携带Cookie
            maxAge: 360000  # 跨域检测有效期