server:
  port: 8888
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  application:
    name: blogservice

  cloud:
    nacos:
      discovery:
        cluster-name: Xian
        namespace: b288257e-bee0-464d-af61-bb397ce42e10
        ephemeral: false

  datasource:
    url: jdbc:mysql://192.168.190.129:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '200058'
    driver-class-name: com.mysql.cj.jdbc.Driver
  #文件上传设置
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  #SpringSecurity默认账号密码
  security:
    user:
      name: root
      password: root
  #redis配置
  redis:
    #数据库索引
    database: 0
    host: 192.168.190.129
    port: 6379
    password: ""
    timeout: 0
    #redis连接池配置

  #开启事务
  transaction:
    rollback-on-commit-failure: true

mybatis-plus:
  configuration:
    #打印日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除字段名
      logic-delete-field: delFlag
      #1代表已删除
      logic-delete-value: 1
      #0代表未删除
      logic-not-delete-value: 0
      #主键自增策略
      id-type: auto
  mapper-locations: classpath*:com/blog/mapper/xml/*.xml

oss:
  accessKey: em2X2-Ra1aWID3I2jHtFbp21OBy0UV7M2WkYVlHG
  secretKey: 7o4xxRuGocTFJk14fC_DmTGdV2gBWCb2cF-_iYgk
  bucket: my-learning

adminservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

# 负载均衡
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: adminservice

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: basic
#  httpclient:
#    enabled: true # 支持HttpClient的开关
#    max-connections: 200 # 最大连接数
#    max-connections-per-route: 50 # 单个路径的最大连接数
