server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver
  #文件上传设置
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  #SpringSecurity默认账号密码
  security:
    user:
      name: root
      password: root
  #redis配置
  redis:
    #数据库索引
    database: 0
    host: localhost
    port: 6379
    password: ""
    timeout: 0
    #redis连接池配置

mybatis-plus:
  configuration:
    #打印日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除字段名
      logic-delete-field: delFlag
      #1代表已删除
      logic-delete-value: 1
      #0代表未删除
      logic-not-delete-value: 0
      #主键自增策略
      id-type: auto
  mapper-locations: classpath*:com/blog/mapper/xml/*.xml

oss:
  accessKey: em2X2-Ra1aWID3I2jHtFbp21OBy0UV7M2WkYVlHG
  secretKey: 7o4xxRuGocTFJk14fC_DmTGdV2gBWCb2cF-_iYgk
  bucket: my-learning