server:
  port: 9999
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  application:
    name: adminservice
  cloud:
    nacos:
      discovery:
        namespace: d7160cc7-7feb-4f19-b8c1-6960128b6f8c
        cluster-name: Xian
        ephemeral: false

  datasource:
    url: jdbc:mysql://localhost:3306/mytest?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver
  #文件上传设置
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  #SpringSecurity默认账号密码
  security:
    user:
      name: root
      password: root
  #redis配置
  redis:
    #数据库索引
    database: 0
    host: localhost
    port: 6379
    password: ""
    timeout: 0
    #redis连接池配置

mybatis-plus:
  configuration:
    #打印日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除字段名
      logic-delete-field: delFlag
      #1代表已删除
      logic-delete-value: 1
      #0代表未删除
      logic-not-delete-value: 0
      #主键自增策略
      id-type: auto
  mapper-locations: classpath*:com/blog/com.blog.mapper/xml/*.xml

blogservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

# 负载均衡
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: blogservice

feign:
  client:
    config:
      default: # 或者是想要调用的微服务名称，default代表全局配置
        loggerLevel: FULL
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
